### ISSUE TITLE
Question about using state and connection pool

### ISSUE THREAD

**Issue by rohanmsunmall** [AThilenius/axum-connect#9]
What is the best way to handle/ cleanest way to handle state in the handlers;  IE in the examples say_hello_unary I want to access a sqlx connection pool and pass in state/reference to the pool as a parameter.

**Comment by AThilenius** [comment]
This question is better answered by the Axum docs: https://docs.rs/axum/latest/axum/#using-the-state-extractor `axum-connect` leans entirely on Axum for all of that, by design.
